### ISSUE TITLE
Error with last release

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/burst-miner#12]
08:10:49: Burst miner 1.4.0

08:12:51: Error on getting new block-info!
08:12:51: Expect either an object or array at root

Work well with 1.3.1

**Comment by Creepsky** [comment]
Seems like your pool dont understand HTTP/1.1
I added a new setting in mining.conf:
"http" : [0/1] (0 for HTTP/1.0 and 1 for HTTP/1.1)

Could you please add this setting ("http" : 0) to your local mining.conf or copy the new mining.conf from release 1.4.0 and test it again?
If it dont work, we need to look further.

**Comment by Pascal66** [comment]
Same error.
The pool seems using the regular server V2.
Here's my mining.conf: 
{
    "poolUrl" : "mining.tompool.org:8124",
    "submissionMaxRetry" : 3,
    "sendMaxRetry" : 3,
    "receiveMaxRetry" : 3,
    "receiveTimeout" : 5,
    "sendTimeout" : 5,
    "maxBufferSizeMB" : 128,
    "http" : 0,
    "output" : [],
    "plots" : 
    [
     "X:\\Burst\\plots",
     "C:\\Burst\\plots",
     "Y:\\Burst\\plots"
	]
 }

**Comment by Creepsky** [comment]
Okay thanks.
I changed the code again. Now the full response from server is shown on an error.
Please download the burst-miner.exe and copy-paste the response when the miner is showing it.

**Comment by Pascal66** [comment]
same error as above :( no exxtra informations

**Comment by Pascal66** [comment]
response with http:1

19:54:18: Http : HTTP/1.1
19:54:18: Pool Host : mining.tompool.org:8124 (155.143.147.21)
19:54:18: Mininginfo URL : mining.tompool.org:8124 (155.143.147.21)
19:56:18: Error on getting new block-info!
19:56:18: Expect either an object or array at root
19:56:18: Full response:
19:56:18:  HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 25 Nov 2016 18:55:13 GMT
Connection: keep-alive
Transfer-Encoding: chunked

9d
{"generationSignature":"07fd295f934a803acaa32a50f921d851be4b3aee03c224a08f52281f380b3b9f","baseTarget":"3534308","requestProcessingTime":0,"height":"299168"}
0

**Comment by Pascal66** [comment]
response with http:0

19:57:53: Http : HTTP/1.0
19:57:53: Pool Host : mining.tompool.org:8124 (155.143.147.21)
19:57:53: Mininginfo URL : mining.tompool.org:8124 (155.143.147.21)
19:57:54: --------------------------------------------------
20:04:10: block#      299173
20:04:10: scoop#      2553
20:04:10: baseTarget# 4056394
20:04:10: --------------------------------------------------
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (33á259y 9m 16d 11:41:44)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (9á858y 8m 11d 02:05:35)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (5á681y 3m 5d 18:31:47)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (472y 10m 1d 06:23:31)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (421y 3m 7d 04:34:20)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (285y 9m 2d 20:07:54)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (133y 8m 20d 12:54:03)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (60y 3m 2d 07:14:28)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (38y 4m 11d 11:40:57)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (9y 8m 22d 14:03:19)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (2y 4m 16d 18:18:22)
20:04:10: V4W6-A7MW-9P3R-CEAYM: nonce found (8m 9d 15:28:44)
20:04:11: V4W6-A7MW-9P3R-CEAYM: nonce found (3m 2d 10:21:00)
20:04:12: V4W6-A7MW-9P3R-CEAYM: nonce found (2m 21d 14:41:56)
20:04:13: V4W6-A7MW-9P3R-CEAYM: nonce found (2m 1d 08:20:59)

**Comment by Creepsky** [comment]
Now I see the problem.
On HTTP/1.1 the mining info is chunked, like the header is saying it: Transfer-Encoding: chunked.
Chunked messages are not implemented yet (coming soon), so better use HTTP/1.0.

I pushed some improvements to release 1.4.0. Please tell me, if there are some bugs or errors.

**Comment by Pascal66** [comment]
New error : 

10:22:42: Mining networking failed

**Comment by Creepsky** [comment]
I checked it with your config file, seems to be working on Windows and Linux.
Mining networking failed means the host could not be resolved.
What is the output when you start the miner?
Should look like this:

> ...

> using config file : mining.conf

> ...

> 13:09:37: Pool Host : mining.tompool.org:8124 (155.143.147.21)

> 13:09:37: Mininginfo URL : mining.tompool.org:8124 (155.143.147.21)


I released version 1.4.1 with some bug fixes.

**Comment by Pascal66** [comment]
It's not resolving the host, just crash

**Comment by Creepsky** [comment]
Please see Version 1.4.2 for more informations while crashing

**Comment by Pascal66** [comment]
Resolved 👍  I have to not put http:// before ..
Feel stupid now but it'ts how it was writed to the website
