### ISSUE TITLE
crash with latest version

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/burst-miner#22]
work with 1.4.2

**Comment by Creepsky** [comment]
When exactly does it crash? Is there any console output before crashing?
Please add the flag "debug" in the configuration under "output" : [ ... , "debug", ... ] for more informations and copy paste it here.

**Comment by Pascal66** [comment]
no information, just crash. but only happen on a computer with : 
CPU support:  SSE  SSE2  SSE3
GenuineIntel Intel(R) Celeron(R) CPU          430  @ 1.80GHz  [1 cores]
RAM: 2048 Mb
since 1.4.2, other computers more recent, all versions works.

**Comment by Creepsky** [comment]
with version 1.4.5 the default cpu instruction set was set to AVX, what is unhappily not supported by your cpu.
I will set the default instruction set to SSE2 again for future releases, other instruction sets will be provided as separate executables (for example burst-miner-avx.exe for AVX).

I recompiled version 1.4.8 and uploaded it again: https://github.com/Creepsky/burst-miner/releases/tag/1.4.8.
Please try **burst-miner.exe**, and only if its not working, the other releases.

**Comment by Pascal66** [comment]
still crash with every version :(

**Comment by Creepsky** [comment]
Strange. Lets do this.
