### ISSUE TITLE
define differents ports

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/burst-miner#23]
14:57:26: Pool Host : 192.168.1.42:8234 (192.168.1.42)
14:57:26: Mininginfo URL : 192.168.1.42:8234 (192.168.1.42)

Is it possible to define an info port different than the pool host ?

**Comment by Pascal66** [comment]
find it in source code the solution : 
if (configDoc.HasMember("poolUrl"))
if (configDoc.HasMember("miningInfoUrl"))
// if no getMiningInfoUrl and port are defined, we assume that the pool is the source

**Comment by Creepsky** [comment]
yes you are fully right,
but this is not fully implemented yet. I will push a new release right now with this functionality (it will be version 1.4.8) :)
