### ISSUE TITLE
msvcp140.dll and vcruntime140.dll missing

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/burst-miner#37]
Was happy for this new release but missing dll on a fresh computer
(work fine on my dev computer)

**Comment by Creepsky** [comment]
You need the [Visual C++ Redistributable für Visual Studio 2015](https://www.microsoft.com/de-de/download/details.aspx?id=48145). I compiled everything with Visual Studio 2015 so it should explain it.

**Comment by Beddhist** [comment]
I ran the installer for 1.7.16 and once complete it threw the same errors. Shouldn't the installer check for this and at least prompt the user to install VC++? At the very least it should be mentioned at the download page.
