### ISSUE TITLE
any plan for an own icon ?

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/burst-miner#40]
Miner icon

**Comment by Creepsky** [comment]
Wow thanks. Have not planned an own icon but I can look for one. Would be a good idea!

**Comment by Pascal66** [comment]
Certainly ;) You made great ehancements, it's time to have one great icon !
Unfortunatly, i'm only a coder, not a designer lol

**Comment by Creepsky** [comment]
How would be this icon here : https://www.iconfinder.com/icons/182515/cat_tied_yarn_icon#size=128 😸

**Comment by Pascal66** [comment]
![burstcreep](https://cloud.githubusercontent.com/assets/3041616/22017337/3ff8a6de-dcaa-11e6-88f0-36cca30cc664.jpg)

**Comment by Creepsky** [comment]
Ok I get the idea.. is there any deadline for this or can we gather some more pics and choose the best one out of them?

**Comment by Pascal66** [comment]
Dont know, it's just an idea.
My idea is to have a long term rememerable icon.
Up to you, you are the owner of your concept

**Comment by Creepsky** [comment]
The idea is good, its just hard to find a good icon that the people will remember and associate with the miner. If you have something, post it please! I will look for one too, maybe even try to design one by myself 😆
Would be nice to have such an icon!

**Comment by Pascal66** [comment]
I'm currently working on the uray pool code, and made many peoples not happy.
If i've time, i try to help you as I always do.
For the moment, I trying to make things clear.

**Comment by Adavan83** [comment]
If i can suggest, icon with "cat" should be fine :). Or this https://www.iconfinder.com/icons/60814/cat_cheshire_halloween_icon#size=128 looks fine too. Just my opinion.
