### ISSUE TITLE
X-Miner Header

### ISSUE THREAD

**Issue by SOELexicon** [Creepsky/burst-miner#41]
Hi Buddy,

i was sent a link here by Nixxda (guelz) i had a request not long ago to add xminer headers and images for each of the different miners. (IceBurst personally requested it so he could see Android miners )

do you want to set your x-Miner header to start with Creepsky and ill add to to the uray source im maintaining for the community. if yes ill add this in now, update the public repo and let the users on the forums know

if you want to get in contact join the burst discord at http://www.discord.io/burstofficial

**Comment by Creepsky** [comment]
Hello,

when I began to rewrite the code from uray, there was no such thing as x-miner so I decided to set it to "creepsky-uray-..." just for testing purposes and never changed it back.

Could you please set the beginning to "creepMINER"? :)

There is no custom icon at the moment (just the official Burstcoin logo). Can I send an icon afterwards or would it be better to rename and set icon at once?

Thank you very much!

**Comment by SOELexicon** [comment]
ive just set it to work off creepsky as long as the x-miner header starts with that it should pick it up.

also for now ive set the image as https://www.iconfinder.com/icons/182515/cat_tied_yarn_icon#size=64

if you want you can send me a new one at any point and ill add it in :)  

below is the commit
https://github.com/SOELexicon/burst-pool/commit/e6090e5883334c2267af7af5898e85a7bd4020cd
