### ISSUE TITLE
Dev version unable to compile in Debian

### ISSUE THREAD

**Issue by Adavan83** [Creepsky/burst-miner#42]
Hello.
I try to compile it in my linux machine, but without success:
```
adavan@Debian:~/BurstCoin/Creepsky_150$ make
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -Isrc/rapidjson -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/sphlib/sph_shabal.cpp -o bin/sphlib/sph_shabal.o
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -Isrc/rapidjson -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/nxt/nxt_address.cpp -o bin/nxt/nxt_address.o
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -Isrc/rapidjson -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Url.cpp -o bin/Url.o
In file included from src/Url.cpp:1:0:
src/Url.hpp:4:22: fatal error: Poco/URI.h: Adresár alebo súbor neexistuje
 #include <Poco/URI.h>
                      ^
compilation terminated.
Makefile:41: recipe for target 'bin/Url.o' failed
make: *** [bin/Url.o] Error 1
```

Next i try to run "install-poco.sh", bud this failed with error to:

```
** Compiling src/CipherFactory.cpp (debug, shared)
g++  -Iinclude -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/CppUnit/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/CppUnit/WinTestRunner/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Foundation/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/XML/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/JSON/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Util/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Net/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Crypto/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/NetSSL_OpenSSL/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Data/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Data/SQLite/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Data/ODBC/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Data/MySQL/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/MongoDB/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Zip/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/PageCompiler/include -I/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/PageCompiler/File2Page/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=Cube -DPOCO_TARGET_OSNAME=Linux -DPOCO_TARGET_OSARCH=x86_64  -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/CipherFactory.cpp -o /home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Crypto/obj/Linux/x86_64/debug_shared/CipherFactory.o
In file included from include/Poco/Crypto/CipherKeyImpl.h:24:0,
                 from include/Poco/Crypto/CipherKey.h:24,
                 from src/CipherFactory.cpp:19:
include/Poco/Crypto/OpenSSLInitializer.h:26:28: fatal error: openssl/crypto.h: Adresár alebo súbor neexistuje
 #include <openssl/crypto.h>
                            ^
compilation terminated.
/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/build/rules/compile:53: recipe for target '/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Crypto/obj/Linux/x86_64/debug_shared/CipherFactory.o' failed
make[1]: *** [/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Crypto/obj/Linux/x86_64/debug_shared/CipherFactory.o] Error 1
make[1]: Leaving directory '/home/lubos/BurstCoin/Creepsky_150/poco-1.7.6-all/Crypto'
Makefile:201: recipe for target 'Crypto-libexec' failed
make: *** [Crypto-libexec] Error 2
```

Next i try install "libpoco-dev" package directly from repositories, but too without success:
```
lubos@Cube:~/BurstCoin/Creepsky_150$ make
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -Isrc/rapidjson -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Url.cpp -o bin/Url.o
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -Isrc/rapidjson -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/MinerLogger.cpp -o bin/MinerLogger.o
src/MinerLogger.cpp: In static member function ‘static void Burst::MinerLogger::printTime()’:
src/MinerLogger.cpp:174:15: error: ‘put_time’ is not a member of ‘std’
  std::cout << std::put_time(std::localtime(&now_c), "%X") << ": ";
               ^
Makefile:41: recipe for target 'bin/MinerLogger.o' failed
make: *** [bin/MinerLogger.o] Error 1
```
I would like to kindly ask you to fix it. Many thanks.

**Comment by Creepsky** [comment]
Hi,
let's look at the error messages.

The first one saying you dont have the poco libraries installed (src/Url.cpp missing), so you tried to install it by calling install-poco.sh, what is not wrong and should be doing well.

However, there you get the error message "missing openssl/crypto.h", what has something to do with openssl. Seems like you have (had) it not installed on your system.
Try this command: `openssl version`, it should post you something like `OpenSSL 1.0.1e-fips 11 Feb 2013`.
If not, try to install [openssl](https://packages.debian.org/de/jessie/openssl) and then repeat building the poco libraries (for example by starting install-poco.sh).

The third message is an error in the burst-miner code (#35, if you remember ;)). I pushed a merge from the master into the development branch and this error should go away.

Hope this helps!

**Comment by Adavan83** [comment]
Hello.

Yes, you have right. My first attempt was without Poco libraries installed. I try to run your script "install-poco.sh", but that compillation process fall down with error.
So, poco is bounded to OpenSSL?

When i run your suggested command, it give me `OpenSSL 1.0.1t  3 May 2016`. It is expected version?

Next i try install Poco directly from repostories, but it is lower version (1.3.6p1-5). In your miner you expect exact version? (Poco v 1.7.6)

And last message, OK, i try it now.

**Comment by Creepsky** [comment]
Your OpenSSL version seems up to date.
Miner use version 1.7.6. Unfortunately in version 1.3.6 the module JSON is not included and because of this your compiler cant find <Poco/JSON/Object.h>.

Hmm my suggestion is: try install_poco.sh again.

**Comment by Adavan83** [comment]
Hello.
After several attempts i have fresh news.
Miner is depended to Poco framework and Poco framework is depended to few modules in system (https://pocoproject.org/download/index.html, see part "External Dependencies"). For successfully compile Poco must be in system installed _development packages with headers files_.
I my situation i must installed package "**libssl-dev**" (see http://superuser.com/questions/371901/openssl-missing-during-configure-how-to-fix). After installation of this package, Poco was compilable :).
After successfully installed Poco, miner was compilable too.
After start miner v150 ... i must create new issue :(.

**Comment by Creepsky** [comment]
Thanks so much for figuring out!
I think this miner needs a "how to install" wiki page with this information included. Maybe you can write your experience down there. Would help a lot linux users. :+1:

**Comment by Adavan83** [comment]
You are welcome :). I thank you for maintain this miner.
OK, sounds good. When you place this dev version as a stable, should be my honor to place a little how to for Debian :).

**Comment by ac0v** [comment]
there is a new repository, which contains a binary version and also all required libpoco stuff. See https://forums.getburst.net/t/the-pocc-has-started-a-linux-package-repository-for-burst/399
