### ISSUE TITLE
winning a Block does not show

### ISSUE THREAD

**Issue by guelz** [Creepsky/burst-miner#43]
Hi
I've been running 1.5.0 pre for a day now and I really like it!-)
And its running very stable so far! 

However I just won my first Block with it and this does not show on local http!-)
[stats](https://i.imgsafe.org/09c7937861.jpg)

I'm not "Gallon.he.China"! just showing that I have a wallet running.

I'm using your Windows binaries.

**Comment by Creepsky** [comment]
Glad to hear that :)
The function should be implemented now properly. Would be nice if you could test it, because I dont win that much blocks ;)

**Comment by guelz** [comment]
I'm happy to throw my "weight" at testing!-) but I have not won another Block jet!-/
